### ISSUE TITLE
Player Join Error

### ISSUE THREAD

**Issue by iZeusi** [jiangdashao/Matrix-Issues#102]
## Console Error
[23:51:35 ERROR]: Could not pass event PlayerJoinEvent to Matrix v1.8.0
java.lang.NullPointerException: null
        at me.rerere.matrix.iIIIIIiiiI.<init>(ub) ~[?:?]
        at me.rerere.matrix.IIIiiIiiII.<init>(mo) ~[?:?]
        at me.rerere.matrix.IiIiiIiiii.<init>(g) ~[?:?]
        at me.rerere.matrix.IiiiIiiIII.iiIIiiiIiI(n) ~[?:?]
        at me.rerere.matrix.IiiiIiiIII.iiIIiiiIiI(n) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor163.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-584]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-584]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-584]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1125) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-584]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-584]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

## When the error happens?
The server starts up, and completes the start up process. The first player then joins, and this error is throw.

# Server Infomation
**Server Version**: Paper-597
**Matrix Version**: 1.8.0
**ProtocolLib Version**: 4.4.0
**Is you config files newest?**: yes

**Comment by jiangdashao** [comment]
delete old config files....
