### ISSUE TITLE
Multiverse-Portals issue

### ISSUE THREAD

**Issue by SlimeDog** [jiangdashao/Matrix-Issues#104]
I guess this is a false positive, although there are no logged errors.

## How you trigger the false positive?
Try to move through MV portal. One arrives in the target world, then is forced back to the portal. This does not occur with Matrix-1.7.5, with everything else the same.

## Verbose Message:
None

## Videos:
None

## Server Information
**Matrix Version**: 1.8.0
**Server Version**: Spigot 1.13.2 latest
**ProtocolLib Version**: 4.4.0-b425
**Multiverse-Core**: 3.0.0-SNAPSHOT-b761
**Multiverse-Portals**: 3.0.0-SNAPSHOT-b790

**Comment by ignPerformance** [comment]
Holy shit. There are a LOT of errors when trying to creating a portal: https://1drv.ms/v/s!ApY4tKsF8vPUgogwr8SbkMmF-dOYkA

[03:48:38] [Server thread/WARN]: [Matrix] Task #71753 for Matrix v1.8.0 generated an exception
java.lang.IllegalArgumentException: receiver cannot be NULL.
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:751) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
	at me.rerere.matrix.IIiiIiIiIi.iiIIiiiIiI(ob) ~[?:?]
	at me.rerere.matrix.iiiiIiIIII.run(mi) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1009) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]

**Comment by SlimeDog** [comment]
Well, I didn't try to create one. I just tried to use existing ones. :(

Why would Matrix generate errors creating a portal? That seems well outside the brief of anti-cheat.

**Comment by jiangdashao** [comment]
I think it was caused by PingSpoof check, the error happened when the check sending a packet to a Null player

**Comment by SlimeDog** [comment]
BTW, my Matrix is configured to log to file, but nothing was logged.

**Comment by jiangdashao** [comment]
It's a strange bug, you can try to delete your log folder to make Matrix regenerate it

**Comment by jiangdashao** [comment]
It was caused by Phase check, fixed it

**Comment by SlimeDog** [comment]
> It's a strange bug, you can try to delete your log folder to make Matrix regenerate it

The log file exists, and it logged version startups. Just no errors. :(

**Comment by jiangdashao** [comment]
I will recode the log system soon™

**Comment by SlimeDog** [comment]
Thank you. The fact that violations aren't reported to the log is pretty serious.

**Comment by SlimeDog** [comment]
Confirmed fixed in Matrix 1.8.1. Thanks.
