### ISSUE TITLE
Doesn't run on the latest paper build [ERROR] 

### ISSUE THREAD

**Issue by explodingcamera** [jiangdashao/Matrix-Issues#1062]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date (both latest version)
- [x] Matrix is running on a 11.15 server
- [x] The issue happens on default config.yml and checks.yml

## Issue Information
```
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: [13:30:36 INFO]: [Matrix] Enabling Matrix v2.8.2
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: [13:30:36 INFO]:    _____
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: [13:30:36 INFO]:   |  |  |   Matrix AntiCheat v2.8.2
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: [13:30:36 INFO]:   |  |  |   Environment: git-Paper-16 (MC: 1.15)
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: [13:30:36 INFO]:
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: [13:30:36 ERROR]: Error occurred while enabling Matrix v2.8.2 (Is it up to date?)
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]: java.lang.NullPointerException: null
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at me.rerere.matrix.IiiIIIiIiI.iIIIiiiIIi(Unknown Source) ~[?:?]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at me.rerere.matrix.IiiiIIIiII.iiIIIiiiiI(Unknown Source) ~[?:?]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at me.rerere.matrix.Matrix.onEnable(Unknown Source) ~[?:?]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[Paper-1.15-b19.jar:git-Paper-16]
Dec 16 13:30:36 scw-brave-cartwright start.sh[29687]:         at java.lang.Thread.run(Thread.java:834) [?:?]
```
## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

All plugins are the same as before the update when everything used to work.

**Comment by jiangdashao** [comment]
1. Redownload Paper
2. Redownload ProtocolLib

And, Github it's not the right place to seek support, you should ask it in the Discord server
