### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by xCustomWorld** [jiangdashao/Matrix-Issues#1154]
## Troubleshooting Information
- [X] Matrix is running on a 1.15.1 paper-32 server
- [X] Matrix and ProtocolLib are up-to-date (latest dev builds of ProtocolLib)
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper-32 MC 1.15.1
**Error(s) found in console**: 
```[Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v3.0.1
java.lang.NullPointerException: null
[10:12:16] [Server thread/WARN]: java.lang.NullPointerException
[10:12:16] [Server thread/WARN]: 	at org.maxgamer.quickshop.Util.SentryErrorReporter.checkWasCauseByQS(SentryErrorReporter.java:140)
[10:12:16] [Server thread/WARN]: 	at org.maxgamer.quickshop.Util.SentryErrorReporter.sendError(SentryErrorReporter.java:202)
[10:12:16] [Server thread/WARN]: 	at org.maxgamer.quickshop.Util.SentryErrorReporter$GlobalExceptionFilter.isLoggable(SentryErrorReporter.java:282)
[10:12:16] [Server thread/WARN]: 	at ch.njol.util.LoggerFilter.isLoggable(LoggerFilter.java:44)
[10:12:16] [Server thread/WARN]: 	at java.util.logging.Logger.log(Logger.java:724)
[10:12:16] [Server thread/WARN]: 	at java.util.logging.Logger.doLog(Logger.java:765)
[10:12:16] [Server thread/WARN]: 	at java.util.logging.Logger.log(Logger.java:876)
[10:12:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:562)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1115)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014)
[10:12:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937)
[10:12:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)```
**How/when does this happen**: From the error, I judge that the plugin is having problems with [QuickShop](https://www.spigotmc.org/resources/quickshop-reremake-1-15-ready-bees-bees-bee.62575/)
**Other information**: The error seems to be on your side. If not, I'll report it to the QuickShop's author. The issue occurs every time player tried to move, and it seems to cause FastBreak/Place false positives. I guess there is some issue with interactions, where QuickShop checks for sign interactions for shop signs, and Matrix checks that too, resulting in mismatch between plugins.

## Configuration Files
**Link to checks.yml file**: Using default config
**Link to config.yml file**: Using default config

**Comment by jiangdashao** [comment]
From your error content, this has nothing to do with matrix
