### ISSUE TITLE
[ERROR] Hitbox

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1206]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Error(s) found in console**: 
[13:18:09] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world and world2
[13:18:09] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:456)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.Location.distance(Location.java:439)
[13:18:09] [Server thread/WARN]: 	at me.rerere.matrix.IiiIiiiiIi.a(Unknown Source)
[13:18:09] [Server thread/WARN]: 	at me.rerere.matrix.IiiIiiiiIi.a(Unknown Source)
[13:18:09] [Server thread/WARN]: 	at me.rerere.matrix.IiiIiiiiIi.a(Unknown Source)
[13:18:09] [Server thread/WARN]: 	at me.rerere.matrix.IiiIiiiiIi.iIIIIIiIii(Unknown Source)
[13:18:09] [Server thread/WARN]: 	at me.rerere.matrix.iiIiIIiIiI.iIIIIIIiII(Unknown Source)
[13:18:09] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
[13:18:09] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:18:09] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[13:18:09] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466)
[13:18:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1112)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[13:18:09] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:18:09] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[13:18:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[13:18:09] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:18:09] [Server thread/INFO]: [Matrix/Error] @HitBox

**How/when does this happen**: /\
**Other information**: By the way dou still setback players after changing worlds?

## Configuration Files
**Link to checks.yml file**: - 
**Link to config.yml file**: -

**Comment by rasputinea** [comment]
this is because you cannot measure distance between 2 locations that are in different worlds, re should just ensure both the player and target are in same dimension

**Comment by DanielAlves123** [comment]
@rasputinea that's right. :)
