### ISSUE TITLE
[ERROR] IllegalArgumentException upon using teleport signs

### ISSUE THREAD

**Issue by Xeonmeister** [jiangdashao/Matrix-Issues#1225]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Error(s) found in console**: IllegalArgumentException
**How/when does this happen**: I have my own plugin which handles teleport signs. If I interact w specific signs i get teleported from the lobby to the skypvp, survival, kitpvp etc. worlds. With the new version when i do this i get an illegal argument exception in the console saying that it cannot mesure distance between the lobby world and the world i teleported to.
**Other information**: This doesn't break anything tho but it looks ugly.

**Comment by jiangdashao** [comment]
Please provide the entire error

**Comment by Xeonmeister** [comment]
[12:38:17] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Matrix v4.0.0
java.lang.IllegalArgumentException: Cannot measure distance between world_sky and world_mini
	at org.bukkit.Location.distanceSquared(Location.java:510) ~[Paper.jar:git-Paper-66]
	at org.bukkit.Location.distance(Location.java:493) ~[Paper.jar:git-Paper-66]
	at me.rerere.matrix.IIIIiIiIII.iIiiiIIiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.IiIIIiIIiI.iIiiiIIiiI(Unknown Source) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor86.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper.jar:git-Paper-66]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper.jar:git-Paper-66]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper.jar:git-Paper-66]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper.jar:git-Paper-66]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[Paper.jar:git-Paper-66]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:137) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1319) ~[?:git-Paper-66]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[Paper.jar:git-Paper-66]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[Paper.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
