### ISSUE TITLE
[ERROR] Could not pass event PlayerMoveEvent to Matrix v4.1.1

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#1311]
## Troubleshooting Information
- [ ] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

This happened yesterday on 4.1.1, but I would doubt 4.2.0 fixed this. And I also do not use default config or checks, because I can't do that on the main server we use, and I doubt I will be able to reproduce this error on an empty server, but I could try run an empty server for days and see.

## Issue Information
**Server version**: 1.8.8
**Error(s) found in console**: 
```
[19:02:40] [Timer-2/ERROR]: ------------------------------
[19:02:40] [Timer-2/ERROR]:         Matrix Watchdog Thread
[19:02:40] [Timer-2/ERROR]: Recent Move:
[19:02:40] [Timer-2/ERROR]: 	UUID: dddbf682-7cf5-483d-96df-1a331d245d58
[19:02:40] [Timer-2/ERROR]: 		Moves: {2019.9753224728556, 28.579698543676116, -1984.7627077318268} | {2019.9956494730568, 29.162141421026988, -1984.47348966091} | {2019.996240593179, 29.162141421026988, -1984.4989628030569} | {2019.9968317133012, 29.08374141950111, -1984.5476165052257} | {2019.9974228334233, 28.928509414984507, -1984.6173645176223} | {2019.9980139535455, 28.697982046071544, -1984.7063083528794} | {2019.9986050736677, 28.393665218614, -1984.812720387443}
[19:02:40] [Timer-2/ERROR]: 	UUID: f64ed839-5b57-4bfb-aaa2-4abb0b55e51e
[19:02:40] [Timer-2/ERROR]: 		Moves: {-17.79613447465461, 35.607999992370594, 13.566960960274617} | {-17.79613447465461, 35.50999999046324, 13.566960960274617} | {2013.5792042537262, 86.90199999809265, -1967.0475610195265} | {2013.5792042537262, 86.8039999961853, -1967.0475610195265} | {2013.5792042537262, 86.70599999427795, -1967.0475610195265} | {2013.5792042537262, 86.6079999923706, -1967.0475610195265} | {2013.5792042537262, 86.50999999046324, -1967.0475610195265}

[... many more Moves errors from lots of players ...]

[19:02:40] [Timer-2/ERROR]: Server stop responding!
[19:02:40] [Timer-2/ERROR]: NMS: v1_8_R3
[19:02:40] [Timer-2/ERROR]: Version: git-SportPaper-"d85121f" (MC: 1.8.8)
[19:02:40] [Timer-2/ERROR]: ------------------------------
[19:02:43] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v4.1.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:569) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventSynchronously(SimplePluginManager.java:527) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:521) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:280) [?:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [sportpaper.jar:git-SportPaper-"d85121f"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.processTasks(MinecraftServer.java:1724) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.processTasks(DedicatedServer.java:397) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:882) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722) [sportpaper.jar:git-SportPaper-"d85121f"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
	at me.rerere.matrix.iiiiiiiIiI.IiiIiIiiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.IiiIiiiiiI.IiiIiIiiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.IiiiiIiIII.IiiIiIiiiI(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	... 31 more
[19:02:45] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v4.1.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:569) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.access$0(SimplePluginManager.java:531) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager$2.callEvent(SimplePluginManager.java:536) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventBody(SimplePluginManager.java:586) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:579) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEventSynchronously(SimplePluginManager.java:527) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:521) [sportpaper.jar:git-SportPaper-"d85121f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:280) [?:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [sportpaper.jar:git-SportPaper-"d85121f"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.processTasks(MinecraftServer.java:1724) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.processTasks(DedicatedServer.java:397) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:882) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821) [sportpaper.jar:git-SportPaper-"d85121f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722) [sportpaper.jar:git-SportPaper-"d85121f"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
	at me.rerere.matrix.iiiiiiiIiI.IiiIiIiiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.IiiIiiiiiI.IiiIiIiiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.IiiiiIiIII.IiiIiIiiiI(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[sportpaper.jar:git-SportPaper-"d85121f"]
	... 31 more
```

**How/when does this happen**: Seemingly at random, server will crash and freeze with the `Could not pass event PlayerMoveEvent` error being **spammed** in the console.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://gist.github.com/2b9350214501cc790ae6663dcf484b80#file-checks-yml
**Link to config.yml file**: https://gist.github.com/2b9350214501cc790ae6663dcf484b80#file-config-yml

Keep in mind that `checks.yml` above is the updated one for Matrix 4.2.0, but it didn't have that many changes that should affect this.

**Comment by jiangdashao** [comment]
Can you provide the entire crash log?
The error is useless

**Comment by Brottweiler** [comment]
@jiangdashao https://gist.github.com/a4075c1b74bfa1db638f8278f696553b

**Comment by jiangdashao** [comment]
I don't know the reason, try 4.2.0

**Comment by Brottweiler** [comment]
Sure, I will try 4.2.0 and report if this happens again.
