### ISSUE TITLE
[ERROR] BLOCK java.lang.NullPointerException

### ISSUE THREAD

**Issue by Bayminkk** [jiangdashao/Matrix-Issues#1364]
Matrix is running on a    paperspigot1.13.2   255

[21:34:11 INFO]: [Matrix/TickTask] Error happened! check: BLOCK type: java.lang.NullPointerException
[21:34:11 INFO]: [Matrix/TickTask] Please report this error to author!
[21:34:11 WARN]: java.lang.NullPointerException
[21:34:11 WARN]:        at me.rerere.matrix.iiIiIiIIiI.iIIiIiIiii(Unknown Source)
[21:34:11 WARN]:        at me.rerere.matrix.IiIiIiiIiI.iIiIiIiiiI(Unknown Source)
[21:34:11 WARN]:        at me.rerere.matrix.iIIIiIIiiI.run(Unknown Source)
[21:34:11 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[21:34:11 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[21:34:11 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[21:34:11 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:34:11 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[21:34:11 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[21:34:11 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:34:11 INFO]: [Matrix/TickTask] Error happened! check: BLOCK type: java.lang.NullPointerException
[21:34:11 INFO]: [Matrix/TickTask] Please report this error to author!

**Comment by jiangdashao** [comment]
Don't use outdated Matrix version
