### ISSUE TITLE
[FP] Fly/jesus

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1519]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(13:29:24) player Fly | ground spoof (expect: --, move: 0.0,0.12,0.0, at: 774.143,33.344,200.594, type: air) (+5) | vl:55 ping:48 tps:20.0 component: fly.gf
(13:29:24) player Jesus | suspicious movement in liquid (motion: 0.0,0.12,0.0, down: STATIONARY_WATER, vel: -0.156, module: solid) (+5) | vl:25 ping:48 tps:20.0 component: jesus.solid
(13:29:26) player Fly | ground spoof (expect: --, move: 0.0,0.12,0.0, at: 773.796,34.404,201.279, type: air) (+5) | vl:60 ping:48 tps:20.0 component: fly.gf
(13:29:26) player Jesus | suspicious movement in liquid (motion: 0.0,0.12,0.0, down: STATIONARY_WATER, vel: -0.156, module: solid) (+5) | vl:30 ping:48 tps:20.0 component: jesus.solid
(13:29:26) player Fly | ground spoof (expect: --, move: 0.0,0.12,0.0, at: 773.796,34.524,201.279, type: air) (+5) | vl:65 ping:48 tps:20.0 component: fly.gf
(13:29:26) player Fly | ground spoof (expect: --, move: 0.0,0.08,0.0, at: 773.796,34.485,201.279, type: air) (+5) | vl:70 ping:48 tps:20.0 component: fly.gf
(13:29:27) player Fly | ground spoof (expect: --, move: 0.0,0.114,0.0, at: 773.796,34.599,201.279, type: air) (+5) | vl:75 ping:48 tps:20.0 component: fly.gf
(13:29:27) player Fly | ground spoof (expect: --, move: 0.0,0.118,0.0, at: 773.796,34.716,201.279, type: air) (+5) | vl:80 ping:48 tps:20.0 component: fly.gf
(13:29:27) player Fly | ground spoof (expect: --, move: 0.0,0.119,0.0, at: 773.796,34.835,201.279, type: air) (+5) | vl:85 ping:48 tps:20.0 component: fly.gf
(13:29:27) player Jesus | suspicious movement in liquid (motion: 0.0,0.12,0.02, down: STATIONARY_WATER, vel: -0.156, module: solid) (+5) | vl:35 ping:48 tps:20.0 component: jesus.solid
(13:29:27) player Fly | ground spoof (expect: --, move: 0.0,0.12,0.02, at: 773.796,34.955,201.298, type: air) (+5) | vl:90 ping:48 tps:20.0 component: fly.gf
(13:29:28) player Fly | ground spoof (expect: --, move: 0.0,0.119,0.0, at: 773.797,35.326,201.364, type: air) (+5) | vl:95 ping:48 tps:20.0 component: fly.gf
(13:29:28) player Jesus | suspicious movement in liquid (motion: 0.0,0.12,0.0, down: STATIONARY_WATER, vel: -0.156, module: solid) (+5) | vl:40 ping:48 tps:20.0 component: jesus.solid

**How/when does this happen**: i was swimming up on 1.12 client in the water and it kicked me
**Video of false positive**: not needed
**Other information**: 1.8 server 1.12 client

## Configuration Files
**Link to checks.yml file**: -

**Comment by DanielAlves123** [comment]
@jiangdashao why close?

**Comment by DanielAlves123** [comment]
@jiangdashao also NPE
Caused by: java.lang.NullPointerException
        at me.rerere.matrix.nms.versions.v1_8_r3.NMS_V1_8_R3.IiIIiiiiII(Unknown Source) ~[?:?]
        at me.rerere.matrix.IIiIiiiIii.IIiiIIiIiI(Unknown Source) ~[?:?]
        at me.rerere.matrix.IIiIIIiIiI.IiIIiiiiII(Unknown Source) ~[?:?]
        at me.rerere.matrix.IIiiiiIiiI.IiIIiiiiII(Unknown Source) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
        ... 16 more
