### ISSUE TITLE
[ERROR] [Matrix/TickTask] Error happened! check: BLOCK type: java.lang.NullPointerException

### ISSUE THREAD

**Issue by honzakucera** [jiangdashao/Matrix-Issues#1571]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date (*running Matrix 4.7.1*)
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2

At one point, which seems to be random, an error starts appearing every tick and the console is completly flooded with it afterwards:
```
[21:31:04] [Server thread/WARN]: java.lang.NullPointerException
[21:31:04] [Server thread/WARN]: 	at me.rerere.matrix.IiiiIiIiII.iiiiiIiiiI(Unknown Source)
[21:31:04] [Server thread/WARN]: 	at me.rerere.matrix.IIiiIiiIIi.IIIiIiIiii(Unknown Source)
[21:31:04] [Server thread/WARN]: 	at me.rerere.matrix.iIIiiiiIIi.run(Unknown Source)
[21:31:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[21:31:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[21:31:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[21:31:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423)
[21:31:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[21:31:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[21:31:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[21:31:04] [Server thread/INFO]: [Matrix/TickTask] Error happened! check: BLOCK type: java.lang.NullPointerException
[21:31:04] [Server thread/INFO]: [Matrix/TickTask] Please report this error to author!
```

This seems to happen randomly once a week (last time today, before that on saturday).
It may somehow be related to this error, which *seems to be* caused by a conflict with AuthMe restricting player movement before login.

```
java.lang.NullPointerException: null
	at me.rerere.matrix.IiiiIiIiII.iiiiiIiiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.IiIIIIIiiI.iiiiiIiiiI(Unknown Source) ~[?:?]
	at me.rerere.matrix.iIiiiIiiII.iiiiiIiiiI(Unknown Source) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor378.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-67]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-67]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-67]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1115) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-67]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-67]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
This happens sometimes right after a player joins the server.
Reloading the plugin or restarting the server fixes everything.

The only things changed in `checks.yml` are:
- replaced all `kick` with `notify`
- translated messages to a different language

I can provide more information if needed.

**Comment by jiangdashao** [comment]
ignore it, not important
