### ISSUE TITLE
[ERROR] NullPointerException

### ISSUE THREAD

**Issue by AoElite** [jiangdashao/Matrix-Issues#1790]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 Latest Paper Build
**Error(s) found in console**: 

[05:06:53] [Craft Scheduler Thread - 1296/INFO]: [Matrix] [AsyncPool] Find a error when run a async task, exception type: java.lang.NullPointerException
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: java.lang.NullPointerException
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at me.rerere.matrix.gB$FC.run(Unknown Source)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at me.rerere.matrix.o.run(Unknown Source)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[05:06:53] [Craft Scheduler Thread - 1296/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**How/when does this happen**: Possibly loading a world.
**Other information**: None
## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by BrokenFG** [comment]
Agree, viewing this exception at least 2 days.
