### ISSUE TITLE
[INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by ydacs** [jiangdashao/Matrix-Issues#1853]
Could not load 'plugins\反作弊Matrix_5.0.0_hotfix_release.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/rerere/matrix/k
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:360) [CraftServer.class:git-CatServer-1.12.2-2124fc5]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:342) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: me/rerere/matrix/k
        at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-2124fc5]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: me.rerere.matrix.k
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-2124fc5]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: me.rerere.matrix.k
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-2124fc5]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-2124fc5]
        ... 7 more

**Comment by jiangdashao** [comment]
Matrix不支持模组服务端

**Comment by ydacs** [comment]
纯净端也不加载
 Could not load 'plugins\反作弊Matrix_5.0.0_hotfix_release.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/rerere/matrix/k
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: me/rerere/matrix/k
        at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: me.rerere.matrix.k
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        ... 6 more

**Comment by jiangdashao** [comment]
请提供完整日志

**Comment by ydacs** [comment]
安装了ProtocolLib 版本4.5.1

[18:49:31] [Server thread/INFO]: Starting minecraft server version 1.12.2
[18:49:31] [Server thread/INFO]: Loading properties
[18:49:31] [Server thread/INFO]: Default game type: SURVIVAL
[18:49:31] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:49:31] [Server thread/INFO]: Debug logging is disabled
[18:49:31] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:49:31] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:49:31] [Server thread/INFO]: Generating keypair
[18:49:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:49:32] [Server thread/INFO]: Using default channel type
[18:49:34] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[18:49:34] [Server thread/ERROR]: Could not load 'plugins\反作弊Matrix_5.0.0_hotfix_release.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/rerere/matrix/k
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: me/rerere/matrix/k
	at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	... 6 more
Caused by: java.lang.ClassNotFoundException: me.rerere.matrix.k
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at me.rerere.matrix.Matrix.<clinit>(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	... 6 more
[18:49:34] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.1
[18:49:35] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.1
[18:49:35] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[18:49:35] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:49:35] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[18:49:35] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[18:49:35] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[18:49:35] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[18:49:35] [Server thread/INFO]: Preparing level "world"
[18:49:35] [Server thread/INFO]: -------- World Settings For [world] --------
[18:49:35] [Server thread/INFO]: Item Despawn Rate: 6000
[18:49:35] [Server thread/INFO]: Item Merge Radius: 2.5
[18:49:35] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:49:35] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:49:35] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:49:35] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:49:35] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:49:35] [Server thread/INFO]: View Distance: 10
[18:49:35] [Server thread/INFO]: Mob Spawn Range: 4
[18:49:35] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:49:35] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[18:49:35] [Server thread/INFO]: Random Lighting Updates: false
[18:49:35] [Server thread/INFO]: Max TNT Explosions: 100
[18:49:35] [Server thread/INFO]: Structure Info Saving: true
[18:49:35] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Vine Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:49:35] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:49:35] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:49:35] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[18:49:35] [Server thread/INFO]: Item Despawn Rate: 6000
[18:49:35] [Server thread/INFO]: Item Merge Radius: 2.5
[18:49:35] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:49:35] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:49:35] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:49:35] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:49:35] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:49:35] [Server thread/INFO]: View Distance: 10
[18:49:35] [Server thread/INFO]: Mob Spawn Range: 4
[18:49:35] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:49:35] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[18:49:35] [Server thread/INFO]: Random Lighting Updates: false
[18:49:35] [Server thread/INFO]: Max TNT Explosions: 100
[18:49:35] [Server thread/INFO]: Structure Info Saving: true
[18:49:35] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Vine Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:49:35] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:49:35] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:49:35] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[18:49:35] [Server thread/INFO]: Item Despawn Rate: 6000
[18:49:35] [Server thread/INFO]: Item Merge Radius: 2.5
[18:49:35] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:49:35] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:49:35] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:49:35] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:49:35] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:49:35] [Server thread/INFO]: View Distance: 10
[18:49:35] [Server thread/INFO]: Mob Spawn Range: 4
[18:49:35] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:49:35] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[18:49:35] [Server thread/INFO]: Random Lighting Updates: false
[18:49:35] [Server thread/INFO]: Max TNT Explosions: 100
[18:49:35] [Server thread/INFO]: Structure Info Saving: true
[18:49:35] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Vine Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[18:49:35] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:49:35] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:49:35] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:49:35] [Server thread/INFO]: Preparing start region for level 0 (Seed: -4081779956019848634)
[18:49:36] [Server thread/INFO]: Preparing start region for level 1 (Seed: -891226435974819986)
[18:49:37] [Server thread/INFO]: Preparing start region for level 2 (Seed: -891226435974819986)
[18:49:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:49:37] [Server thread/INFO]: Done (2.606s)! For help, type "help" or "?"
[18:49:37] [Server thread/INFO]: Starting remote control listener
[18:49:37] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:1992

**Comment by jiangdashao** [comment]
请重新下载Matrix最新版
