### ISSUE TITLE
[ERROR] Async task console error

### ISSUE THREAD

**Issue by AoElite** [jiangdashao/Matrix-Issues#1870]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tuinity-b492d81 (Fork of paper 1.15.2)
**Error(s) found in console**: 
```
[22:41:15] [Server thread/INFO]: Spawned KillAura Npc for hiyouv2 (100 ticks)
[22:41:15] [Craft Scheduler Thread - 1085/INFO]: [Matrix] [AsyncPool] Find a error when run a async task, exception type: java.lang.RuntimeException
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: java.lang.RuntimeException: An internal error occured.
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:509)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:521)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at me.rerere.matrix.ca.a(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at me.rerere.matrix.ca.e(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at me.rerere.matrix.ca.t(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at me.rerere.matrix.ca.e(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at me.rerere.matrix.iA$KC.run(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at me.rerere.matrix.P.run(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: Caused by: java.lang.IllegalArgumentException: Duplicate id value for 8!
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at net.minecraft.server.v1_15_R1.DataWatcher.register(DataWatcher.java:81)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[22:41:15] [Craft Scheduler Thread - 1085/WARN]: 	... 14 more
```

**How/when does this happen**: Maybe when an NPC is spawned on a player, not sure.

**Comment by jiangdashao** [comment]
Does this error happen every time NPC spawns?

**Comment by AoElite** [comment]
No. Also, I don't know what's causing it, the only reason I said it could be an NPC was that "Spawned KillAura Npc for hiyouv2" was outputted right before the error.
