### ISSUE TITLE
[ERROR] NPC

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#1881]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-0509002-7c03d25 (MC: 1.16.1)
**Error(s) found in console**: 
[19:51:47] [Server thread/WARN]: [Matrix] Task #8 for Matrix v5.1.0 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at me.rerere.matrix.aa.c(Unknown Source) ~[?:?]
        at me.rerere.matrix.aa.u(Unknown Source) ~[?:?]
        at me.rerere.matrix.Gc.c(Unknown Source) ~[?:?]
        at me.rerere.matrix.pb.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0509002-7c03d25]
        at java.lang.Thread.run(Thread.java:832) [?:?]
**How/when does this happen**:  I get this error right after matrix spawns an npc. 
**Other information**: It's not kicking me for killaura.

## Configuration Files
[config.zip](https://github.com/jiangdashao/Matrix-Issues/files/4990296/config.zip)

**Comment by jiangdashao** [comment]
update ProtocolLib to the latest dev build
