### ISSUE TITLE
[ERROR] Errors in console

### ISSUE THREAD

**Issue by s7an1slaw** [jiangdashao/Matrix-Issues#1901]
[16:06:27] [Server thread/INFO]: Spawned KillAura Npc for s7an1slaw (100 ticks)
[16:06:27] [Server thread/WARN]: [Matrix] Task #430 for Matrix v5.1.2 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
	at me.rerere.matrix.Aa.e(Unknown Source) ~[?:?]
	at me.rerere.matrix.Aa.x(Unknown Source) ~[?:?]
	at me.rerere.matrix.Hd.e(Unknown Source) ~[?:?]
	at me.rerere.matrix.Kc.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[16:06:27] [Server thread/INFO]: [Matrix] s7an1slaw might be using combat hacks (KillAura)
[16:06:27] [Server thread/INFO]: [Matrix] s7an1slaw is using combat hacks (KillAura) #2
[16:06:27] [Server thread/INFO]: [Matrix] s7an1slaw tried to move faster than usual (Speed) #1
[16:06:27] [Server thread/INFO]: Delayed 12 seconds to execute the command: matrix kick s7an1slaw KillAura
[16:06:28] [Server thread/INFO]: [Matrix] s7an1slaw tried to reach entity outside max reach distance (HitBox)
[16:06:28] [Server thread/INFO]: Spawned KillAura Npc for s7an1slaw (120 ticks)
[16:06:28] [Server thread/WARN]: [Matrix] Task #430 for Matrix v5.1.2 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
	at me.rerere.matrix.Aa.e(Unknown Source) ~[?:?]
	at me.rerere.matrix.Aa.x(Unknown Source) ~[?:?]
	at me.rerere.matrix.Hd.e(Unknown Source) ~[?:?]
	at me.rerere.matrix.Kc.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by jiangdashao** [comment]
update ProtocolLib
