### ISSUE TITLE
[ERROR] Matrix Server Crash

### ISSUE THREAD

**Issue by AoElite** [jiangdashao/Matrix-Issues#2006]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Error(s) found in console**: 

> [20:27:21] [Paper RegionFile IO Thread/FATAL]: Failed to read chunk data for task: Task for world: 'gladiatorslatest106' at 627,3186 poi: false, hash: 1271515742
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150) ~[?:?]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:790) ~[?:?]
	at net.minecraft.server.v1_15_R1.RegionFile.a(RegionFile.java:558) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at net.minecraft.server.v1_15_R1.RegionFileCache.readFromRegionFile(RegionFileCache.java:177) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at net.minecraft.server.v1_15_R1.RegionFileCache.read(RegionFileCache.java:170) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.read(PlayerChunkMap.java:1586) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at net.minecraft.server.v1_15_R1.WorldServer$2.readData(WorldServer.java:149) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:509) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.15.2.jar:git-Tuinity-"ae2d7fc"]
[20:27:21] [Paper Async Chunk Urgent Task Thread/ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'gladiatorslatest106', (627,3186), hashcode:1599085967, priority: -1, file IO thread has dumped the relevant exception above
[20:27:31] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Tuinity-"ae2d7fc" (MC: 1.15.2) ---
[20:27:31] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[20:27:31] [Paper Watchdog Thread/ERROR]: ------------------------------
[20:27:31] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:27:31] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[20:27:31] [Paper Watchdog Thread/ERROR]: 627,3186 in 'gladiatorslatest106:
[20:27:31] [Paper Watchdog Thread/ERROR]: Load Task - none
[20:27:31] [Paper Watchdog Thread/ERROR]: Save Task - none
[20:27:31] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[20:27:31] [Paper Watchdog Thread/ERROR]: Chunk Status - null chunk
[20:27:31] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[20:27:31] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - null
[20:27:31] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[20:27:31] [Paper Watchdog Thread/ERROR]: Handling packet for player 'Asyn1x', UUID: 10e0b648-8dd5-47d3-b874-1c25c83e8096
[20:27:31] [Paper Watchdog Thread/ERROR]: Position: world: 'Gladiators(Latest1)' at location (6982.5, 43.5, 6837.5)
[20:27:31] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 6703519
[20:27:31] [Paper Watchdog Thread/ERROR]: ------------------------------
[20:27:31] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[20:27:31] [Paper Watchdog Thread/ERROR]: 	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[20:27:31] [Paper Watchdog Thread/ERROR]: 	Stack:
[20:27:31] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.6/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:667)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:335)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:280)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.World.getType(World.java:689)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getType(CraftBlock.java:210)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		me.rerere.matrix.ya.o(Unknown Source)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		me.rerere.matrix.xC.r(Unknown Source)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		me.rerere.matrix.rb.r(Unknown Source)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.plugin.EventExecutor$$Lambda$3014/0x0000000800c2b840.execute(Unknown Source)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1165)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4399/0x000000080133b840.run(Unknown Source)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1163)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1156)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1132)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[20:27:31] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
[20:27:31] [Paper Watchdog Thread/ERROR]: ------------------------------
[20:27:31] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:27:31] [Paper Watchdog Thread/ERROR]: ------------------------------

**How/when does this happen**: No idea
**Other information**: It appears to be a matrix issue because that's the only plugin I see in the mess above.

## Configuration Files
**Link to checks.yml file**: (Default)
**Link to config.yml file**: (Default)

**Comment by AoElite** [comment]
After closer inspection, it appears Matrix is trying to get a block sync and it just hangs the game thread.

**Comment by jiangdashao** [comment]
What's wrong with getting the block type in the main thread? There is a problem with your server, which prevents the block from being obtained, which is probably related to the above error

**Comment by AoElite** [comment]
There is nothing wrong with getting the block type in the main thread. I was just stating that it is.
