### ISSUE TITLE
[ERROR] Could not pass event PlayerJoinEvent to Matrix v5.2.1

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#2059]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Error(s) found in console**: 
[05:15:51] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Matrix v5.2.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:877) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at org.bukkit.permissions.PermissibleBase.hasPermission(PermissibleBase.java:72) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at me.rerere.matrix.ec.r(pc) ~[?:?]
	at me.rerere.matrix.ec.r(pc) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	... 15 more

**How/when does this happen**: join the server, sometimes it can happen
**Other information**: 1.16.3 client

## Configuration Files
**Link to checks.yml file**: 0
**Link to config.yml file**:0

**Comment by jiangdashao** [comment]
check your shit permission plugin

**Comment by assasin541** [comment]
@jiangdashao check your shit anticheat plugin without async. I don't use ANY permissions plugin.
