### ISSUE TITLE
[ERROR] Could not pass event BlockPlaceEvent to Matrix v5.6.3

### ISSUE THREAD

**Issue by EkonC** [jiangdashao/Matrix-Issues#2184]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
This server is running Paper version git-Paper-345 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
**Error(s) found in console**: 
```
>.... [16:30:38 ERROR]: Could not pass event BlockPlaceEvent to Matrix v5.6.3
java.lang.NullPointerException: null
at me.rerere.matrix.lIIllIllllIIlII.IlIIIlIllIlIIIl(uk) ~[?:?]
at me.rerere.matrix.lIllIIlIlIIIlll.IlIIIlIllIlIIIl(al) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor113.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-345]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:378) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:285) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:533) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[?:git-Paper-345]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-345]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-345]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
**How/when does this happen**: 
When players place blocks (not always but I don't know why it happens sometimes and sometimes it doesn't)
**Other Information**:
This has been happening since 5.6.2, I thought 5.6.3 will solve this but it didn't. It doesn't happen in default config.
**Plugins**:
AdvancedEnchantments, AdvancedMonthlyCrates, BossShopPro, BottledExp, Citizens, CMI, CMIPaperLib, CoreProtect, CraftingStore, CustomCrafting, DiscordSRV, DragonSlayer, InventoryRollback, Jobs, LuckPerms, Matrix, MobFarmManager, Multiverse-Core, PlaceholderAPI, Plan, PlayerShops, ProtectionLib*, ProtocolLib, QuickShop, Residence, SkinsRestorer, TAB, TradeMe, TryMe, TutorialCreator, UltimateCatcher, Vault, Votifier, VotingPlugin, WolfyUtilities, WorldEdit, WorldEditGlobalizerBukkit*, WorldGuard, WorldGuardExtraFlags

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/0pX7YE23
**Link to config.yml file**: https://pastebin.com/jS685Khr

**Comment by jiangdashao** [comment]
update or reset your checks.yml
why you can't read the update log?
