### ISSUE TITLE
[ERROR] Old config causes error

### ISSUE THREAD

**Issue by RoccoDev** [jiangdashao/Matrix-Issues#2206]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date (5.6.3)
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml **(it does not occur)**
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running CraftBukkit version git-PaperSpigot-"1987fefb0" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT). Custom fork available at [ProjectKig/KigPaper](https://github.com/ProjectKig/KigPaper).  
**Error(s) found in console**: 
```
[11:20:29 INFO]: [Matrix] Checking Environment...
[11:20:29 INFO]: [Matrix] Passed all environment checks
[11:20:29 INFO]: [Matrix] Initializing the NMSVisitor (v1_8_R3)
[11:20:29 INFO]: [Matrix] Enabled 12 checks, Disabled 3 checks
[11:20:29 INFO]: [Matrix] Loaded all configuration files
[11:20:29 WARN]: java.lang.NullPointerException
[11:20:29 WARN]:        at me.rerere.matrix.IIIIIlIIIIlllII.IlIlllIllllIIlI(le)
[11:20:29 WARN]:        at me.rerere.matrix.IlllIIlllllIIIl.IllllIllIlIlIlI(td)
[11:20:29 WARN]:        at java.util.ArrayList.forEach(ArrayList.java:1259)
[11:20:29 WARN]:        at me.rerere.matrix.lIIlIIlIIlIIlll.<init>(df)
[11:20:29 WARN]:        at me.rerere.matrix.llIIlIllIllllII.<init>(ec)
[11:20:29 WARN]:        at me.rerere.matrix.Matrix.onEnable(dj)
[11:20:29 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[11:20:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[11:20:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[11:20:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:321)
[11:20:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:280)
[11:20:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[11:20:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[11:20:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[11:20:29 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:270)
[11:20:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:566)
[11:20:29 WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:20:29 INFO]: [Matrix] (!) Error when load checks, please check your config files!
[11:20:29 INFO]: [Matrix] Scanning outdated log files....
[11:20:29 INFO]: [Matrix] Deleted 0 outdated log files!
[11:20:29 INFO]: [Matrix] Welcome to Matrix!
```
**How/when does this happen**: When the server starts. Seems to only be caused by a config from an older version. (I recall starting with 5.2, then moving to 5.4, then 5.6.3)
**Other information**: All the features seem to be working fine

## Configuration Files
Both config files available here: https://gist.github.com/RoccoDev/4e966ca386b69b200f490f59ca6bf291

**Comment by NikV2** [comment]
Thats expected, u should delete ur old config files if the changelog says so. Not a matrix issue

**Comment by jiangdashao** [comment]
outdated config(checks.yml)
