### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by MasonKidder345** [jiangdashao/Matrix-Issues#2361]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16
**Error(s) found in console**:
```
 [13:38:57 ERROR]: Could not pass event PlayerJoinEvent to Matrix v6.1.1
java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
        at me.rerere.matrix.lIIIllllllIIIII.lIlIIIIIIIllIll(la) ~[?:?]
        at me.rerere.matrix.lIIIIlIlIllIIII.<init>(sg) ~[?:?]
        at me.rerere.matrix.IIIIlIIlllllllI.IllllllIlIIlllI(gl) ~[?:?]
        at me.rerere.matrix.IIIIlIIlllllllI.lIlIIIllIIllIlI(gl) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor238.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:314) ~[?:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:163) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1568) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:421) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Airplane-"f5fb024"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] 
```
**How/when does this happen**: When a player joins
**Other information**: This is the trial version btw after I updated it since there was a new update then I started to receive this error message whenever a player would join.

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/raw/t0CZLppv
**Link to config.yml file**: https://pastebin.com/raw/M40JWHEz

**Comment by jiangdashao** [comment]
use floodgate2
