### ISSUE TITLE
[ERROR] Java 16 Support

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2378]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 3056-Spigot-4225eac-6f55b5b (MC: **1.16.5)**
**Error(s) found in console**: 
[17:33:23] [Server thread/WARN]: (Matrix) | Failed to inject PlayerConnection.class: java.lang.reflect.InaccessibleObjectException
[17:33:23] [Server thread/WARN]: (Matrix) | Current Loader: jdk.internal.loader.ClassLoaders$AppClassLoader

and

[17:33:33] [Craft Scheduler Thread - 2/WARN]: [Matrix] Plugin Matrix v6.1.1 generated an exception while executing task 23
java.lang.IllegalAccessError: class me.rerere.matrix.IIlIlIlIlIlIIlI (in unnamed module @0x50679ed5) cannot access class sun.net.www.protocol.http.AuthCacheImpl (in module java.base) because module java.base does not export sun.net.www.protocol.http to unnamed module @0x50679ed5
        at me.rerere.matrix.IIlIlIlIlIlIIlI.IIlllllIlllIIlI(fj) ~[?:?]
        at me.rerere.matrix.llIllIllIllllIl.llIIllllIllllIl(uk) ~[?:?]
        at me.rerere.matrix.llIllIllIllllIl.llllIIIIIlIllII(uk) ~[?:?]
        at me.rerere.matrix.IllIlIlIIlllllI.lIIlIIIlllIlIIl(fa) ~[?:?]
        at me.rerere.matrix.IIlIlIIlIllIIIl.lIlllIIllIlIlIl(ca) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:3056-Spigot-4225eac-6f55b5b]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5.jar:3056-Spigot-4225eac-6f55b5b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:33:33] [Craft Scheduler Thread - 1/WARN]: [Matrix] Plugin Matrix v6.1.1 generated an exception while executing task 22
java.lang.IllegalAccessError: class me.rerere.matrix.IIlIlIlIlIlIIlI (in unnamed module @0x50679ed5) cannot access class sun.net.www.protocol.http.AuthCacheImpl (in module java.base) because module java.base does not export sun.net.www.protocol.http to unnamed module @0x50679ed5
        at me.rerere.matrix.IIlIlIlIlIlIIlI.IIlllllIlllIIlI(fj) ~[?:?]
        at me.rerere.matrix.llIllIllIllllIl.llIIllllIllllIl(uk) ~[?:?]
        at me.rerere.matrix.llIllIllIllllIl.llllIIIIIlIllII(uk) ~[?:?]
        at me.rerere.matrix.IlIIlIllllIIlII.lIIIlIlIIllllII(hl) ~[?:?]
        at me.rerere.matrix.IlIIlIllllIIlII.llIIIlIIlIIIlIl(hl) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:3056-Spigot-4225eac-6f55b5b]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5.jar:3056-Spigot-4225eac-6f55b5b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
**How/when does this happen**: When using Java 16
**Other information**: Mojang announced that they will switch to java 16 with the minecraft 1.17 update. ProtocolLib already added java 16 support (make sure to update it before testing), so i'm sure it will be possible here as well.

**Comment by jiangdashao** [comment]
I hate java module system😡

**Comment by steviebeenz** [comment]
> I hate java module system😡

You may need to inject Java 8 rt into the jvm to do some things. It fixed a load of issues for me.
