### ISSUE TITLE
PlayerJoinEvent Issue

### ISSUE THREAD

**Issue by MasonKidder345** [jiangdashao/Matrix-Issues#2398]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Error(s) found in console**: java.lang.NoClassDefFoundError: us/myles/ViaVersion/bukkit/platform/BukkitViaAPI
        at me.rerere.matrix.llIllIlIllIIIII.IIlIllIlIIllIIl(ia) ~[?:?]
        at me.rerere.matrix.lIIIIlIlIllIIII.<init>(sg) ~[?:?]
        at me.rerere.matrix.IIIIlIIlllllllI.IllllllIlIIlllI(gl) ~[?:?]
        at me.rerere.matrix.IIIIlIIlllllllI.lIlIIIllIIllIlI(gl) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor252.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[?:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:164) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1578) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:422) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1398) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.bukkit.platform.BukkitViaAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 20 more
**How/when does this happen**: When a player joins
**Other information**:

**Comment by DontNeedAName** [comment]
Update to latest hotfix.

**Comment by MasonKidder345** [comment]
I'm using the latest version of hotfix, 6.1 right?

**Comment by DontNeedAName** [comment]
6.1.1 hotfix 14 is the latest for trial version.

**Comment by MasonKidder345** [comment]
Okay yes I am using the latest version but I still get this error whenever a player joins so

**Comment by jiangdashao** [comment]
Update your Matrix
