### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by TravoQur** [jiangdashao/Matrix-Issues#2404]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Error(s) found in console**: 
[18:45:00 ERROR]: Could not pass event PlayerJoinEvent to Matrix v6.1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoClassDefFoundError: us/myles/ViaVersion/bukkit/platform/BukkitViaAPI
        at me.rerere.matrix.lIIIlIllIllllII.IlIIIllllIIIllI(oa) ~[?:?]
        at me.rerere.matrix.IlIIllIllIlIIlI.<init>(rn) ~[?:?]
        at me.rerere.matrix.lIIIIllIlIllIll.IlIlllIllllIIII(xj) ~[?:?]
        at me.rerere.matrix.lIIIIllIlIllIll.lIIIIIlIllIllIl(xj) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-3d850ec-809c399]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.bukkit.platform.BukkitViaAPI
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-3d850ec-809c399]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at me.rerere.matrix.lIIIlIllIllllII.IlIIIllllIIIllI(oa) ~[?:?]
        at me.rerere.matrix.IlIIllIllIlIIlI.<init>(rn) ~[?:?]
        at me.rerere.matrix.lIIIIllIlIllIll.IlIlllIllllIIII(xj) ~[?:?]
        at me.rerere.matrix.lIIIIllIlIllIll.lIIIIIlIllIllIl(xj) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-3d850ec-809c399]
        ... 14 more
**How/when does this happen**: ALL
**Other information**: Update Viaversion and SkinRestorer

## Configuration Files
**Link to checks.yml file**: default, first launch
**Link to config.yml file**: default, first launch

**Comment by jiangdashao** [comment]
Update Matrix
