### ISSUE TITLE
[ERROR] Tryin' to modify kick reason

### ISSUE THREAD

**Issue by RoLEX4676** [jiangdashao/Matrix-Issues#2422]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.17.1
**Error(s) found in console**: [01:05:53 INFO]: [Matrix] Initializing the NMSVisitor (v1_17_R1)
[01:05:53 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 412, column 5:
        20: 'matrix notify %player% trie ...
        ^
expected <block end>, but found '<scalar>'
 in 'string', line 414, column 37:
        50: 'matrix kick %player% &cYou've got kick from &a[&bANTICHEAT& ...
                                        ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Paper-97]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Paper-97]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:217) ~[patched_1.17.1.jar:git-Paper-97]
**How/when does this happen**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/kdprcY1H
**Link to config.yml file**: https://pastebin.com/YEnyXAYH

**Comment by jiangdashao** [comment]
check your yaml syntax, not matrix issue
