### ISSUE TITLE
Matrix spam message on my server !

### ISSUE THREAD

**Issue by rater456** [jiangdashao/Matrix-Issues#245]
[03:02:20] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v1.8.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:946) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
	at me.rerere.matrix.IIiiIiiiii.IIIiiiiIiI(j) ~[?:?]
	at me.rerere.matrix.iiiIIiIiii.IIIiiiiIiI(fb) ~[?:?]
	at me.rerere.matrix.IIIiiiiIiI.IIIiiiiIiI(da) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	... 15 more
[03:02:20] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v1.8.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:946) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
	at me.rerere.matrix.IIiiIiiiii.IIIiiiiIiI(j) ~[?:?]
	at me.rerere.matrix.iiiIIiIiii.IIIiiiiIiI(fb) ~[?:?]
	at me.rerere.matrix.IIIiiiiIiI.IIIiiiiIiI(da) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	... 15 more
[03:02:20] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v1.8.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:946) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
	at me.rerere.matrix.IIiiIiiiii.IIIiiiiIiI(j) ~[?:?]
	at me.rerere.matrix.iiiIIiIiii.IIIiiiiIiI(fb) ~[?:?]
	at me.rerere.matrix.IIIiiiiIiI.IIIiiiiIiI(da) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	... 15 more
[03:02:21] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Matrix v1.8.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:240) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1242) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
	at me.rerere.matrix.IIiiIiiiii.IIIiiiiIiI(j) ~[?:?]
	at me.rerere.matrix.iiIIIiiiiI.IIIiiiiIiI(vc) ~[?:?]
	at me.rerere.matrix.IIIiiiiIiI.IIIiiiiIiI(da) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	... 17 more
[03:02:21] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v1.8.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:946) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
	at me.rerere.matrix.IIiiIiiiii.IIIiiiiIiI(j) ~[?:?]
	at me.rerere.matrix.iiiIIiIiii.IIIiiiiIiI(fb) ~[?:?]
	at me.rerere.matrix.IIIiiiiIiI.IIIiiiiIiI(da) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-a639ae4]
	... 15 more

**Comment by jiangdashao** [comment]
Please redownload the spigot jar
spigot: https://getbukkit.org/download/spigot
paper: https://papermc.io/
