### ISSUE TITLE
Protocol Lib 4.4.0 not working for Matrix ?

### ISSUE THREAD

**Issue by Blackyvk** [jiangdashao/Matrix-Issues#26]
## Console Error
```
[08:22:24] [Server thread/ERROR]: Could not load 'plugins/Matrix.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.13.2.jar:git-Paper-546]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330) ~[patched_1.13.2.jar:git-Paper-546]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:277) ~[patched_1.13.2.jar:git-Paper-546]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-546]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-546]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-546]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62) ~[patched_1.13.2.jar:git-Paper-546]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-546]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-546]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-546]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62) ~[patched_1.13.2.jar:git-Paper-546]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-546]
	... 6 more
```

# Server Infomation
**Server Version**: 1.13.2
**Matrix Version**: 1.2.1
**ProtocolLib Version**: 4.4.0 #425
**Is you config files newest?**: yes

**Comment by Blackyvk** [comment]
I found the issue, it seems an incompatibility with FAWE

https://empcraft.com/fawe/download/?bukkit113

any idea why ?

**Comment by jiangdashao** [comment]
I don't know, I will try it later

**Comment by jiangdashao** [comment]
It works for me
