### ISSUE TITLE
[ERROR] Console error MyPet

### ISSUE THREAD

**Issue by artemati1** [jiangdashao/Matrix-Issues#269]
## Basic Information
**Error found in console:**: 
[15:54:57] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v1.9.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1598]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1598]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1598]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1598]
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1098) ~[?:?]
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:952) ~[?:?]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:2024) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247) ~[patched_1.12.2.jar:git-Paper-1598]
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1158) ~[?:?]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1767) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1598]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1598]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassCastException

# Server Infomation
**Server Version: 1.12.2**: 
**Matrix Version: 1.9.0**:

**Comment by jiangdashao** [comment]
Please provide complete error

**Comment by artemati1** [comment]
that's all

**Comment by jiangdashao** [comment]
No, that's not complete
There are more error information under "Caused by: java.lang.ClassCastException"

**Comment by artemati1** [comment]
But that's all
![inOknXJV-4U](https://user-images.githubusercontent.com/49755854/56470928-cf551180-6454-11e9-9a78-67cd6d6c62df.jpg)

**Comment by ignPerformance** [comment]
Look in your server logs for the complete error, please. There's no way that's the full error. @artemati1

**Comment by jiangdashao** [comment]
When does the error happen?

**Comment by artemati1** [comment]
Error disappeared after server reboot
