### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by mastabaaudio** [jiangdashao/Matrix-Issues#345]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14 latest
**Error(s) found in console**: 
[11:00:35] [Netty Epoll Server IO #0/ERROR]: [Matrix] Unhandled exception occured in onPacketReceiving(PacketEvent) for Matrix
java.lang.IllegalStateException: PlayerViolationEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at me.rerere.matrix.iIIiiiiIii.IiiiIiiiII(xc) ~[Matrix.jar:?]
	at me.rerere.matrix.IIIiiiIiiI.IiiiIiiiII(mj) ~[Matrix.jar:?]
	at me.rerere.matrix.iiIIiIIiII.onPacketReceiving(nb) ~[Matrix.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.4.0-b425]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.4.0-b425]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.4.0-b425]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.4.0-b425]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.4.0-b425]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.4.0-b425]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:509) [ProtocolLib.jar:4.4.0-b425]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib.jar:4.4.0-b425]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.14-vanilla.jar:git-Spigot-1eece4f-d5c2e3c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[11:00:35] [Netty Epoll Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayInBlockDig@41b927fe[
    a=BlockPosition{x=198000, y=62, z=-145857}
    b=up
    c=STOP_DESTROY_BLOCK
  ]

**How/when does this happen**: very frequently

**Comment by jiangdashao** [comment]
Same as #344
