### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by habbo1998** [jiangdashao/Matrix-Issues#38]
## Console Error
<> [12:11:33 ERROR]: Could not pass event PlayerInteractEvent to Matrix v1.4.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:205) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1152) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
at me.rerere.matrix.IiIIiIIiii.iiiIIiIiiI(v) ~[?:?]
at me.rerere.matrix.iiIIiiIIii.iiiIIiIiiI(uc) ~[?:?]
at me.rerere.matrix.IiIIiiIIII.iiiIIiIiiI(sa) ~[?:?]
at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
... 18 more
> [12:11:33 ERROR]: Could not pass event BlockBreakEvent to Matrix v1.4.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1166) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getBoundingBox()Lorg/bukkit/util/BoundingBox;
at me.rerere.matrix.IiIIiIIiii.iiiIIiIiiI(v) ~[?:?]
at me.rerere.matrix.iiIIiiIIii.iiiIIiIiiI(uc) ~[?:?]
at me.rerere.matrix.IiIIiiIIII.iiiIIiIiiI(sa) ~[?:?]
at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-fe3ab0d-162bda9]
... 17 more>

## When the error happens?
<Every time a player breaks something or enters>

# Server Infomation
**Server Version**: 1.13 with ViaVersione and ViaRewind
**Matrix Version**: 1.4.5 Model 5
**ProtocolLib Version**: 4.4.0
**Is you config files newest?**: Yes
[2019-03-15-6.log](https://github.com/jiangdashao/Matrix-Issues/files/2970935/2019-03-15-6.log)

**Comment by jiangdashao** [comment]
Please update your spigot to 1.13_R_2

**Comment by habbo1998** [comment]
I will try, thanks!
