### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by pisikain** [jiangdashao/Matrix-Issues#383]
09:54:28] [Netty Epoll Server IO #3/ERROR]: [Matrix] Unhandled exception occured in onPacketReceiving(PacketEvent) for Matrix
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketEvent.isPlayerTemporary()Z
	at me.rerere.matrix.iiIiiiIiIi.onPacketReceiving(eb) ~[Matrix.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.1]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:54:28] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload@54645eae[
    a=REGISTER
    b=UnpooledHeapByteBuf(ridx: 0, widx: 27, cap: 27)
  ]

[09:54:28] [Netty Epoll Server IO #3/ERROR]: [Matrix] Unhandled exception occured in onPacketReceiving(PacketEvent) for Matrix
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketEvent.isPlayerTemporary()Z
	at me.rerere.matrix.iiIiiiIiIi.onPacketReceiving(eb) ~[Matrix.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.1]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:54:28] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload@ea016c6[
    a=MC|Brand
    b=UnpooledHeapByteBuf(ridx: 0, widx: 8, cap: 8)
  ]

[09:54:28] [Netty Epoll Server IO #3/ERROR]: [Matrix] Unhandled exception occured in onPacketReceiving(PacketEvent) for Matrix
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketEvent.isPlayerTemporary()Z
	at me.rerere.matrix.iiIiiiIiIi.onPacketReceiving(eb) ~[Matrix.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.1]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server8.jar:git-PaperSpigot-d709888-d3e0b6f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:54:28] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInSettings@29930886[
    a=ru_ru
    b=32
    c=FULL
    d=true
    e=127
  ]

**Comment by jiangdashao** [comment]
Please update your ProtocolLib
