### ISSUE TITLE
[ERROR] Getting an error when a player joins....

### ISSUE THREAD

**Issue by Smartjer123** [jiangdashao/Matrix-Issues#405]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [*] Matrix and ProtocolLib are up-to-date
- [*] Matrix is running on a 1.12 and 1.13 server
- [*] The issue happens on default config.yml and checks.yml
- [*] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper Spigot (Bungeecord)
**Error(s) found in console**: 
[22:55:38 ERROR]: Could not pass event PlayerJoinEvent to Matrix v1.10.1
java.lang.NullPointerException: null
at me.rerere.matrix.iIiIIiiiIi.<init>(on) ~[?:?]
at me.rerere.matrix.iiiiiiIiiI.<init>(zn) ~[?:?]
at me.rerere.matrix.IiIIiiIiii.<init>(ob) ~[?:?]
at me.rerere.matrix.iIiIIIiiii.IiIIIIIiii(eb) ~[?:?]
at me.rerere.matrix.iIiIIIiiii.IiIIIIIiii(eb) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor317.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
> [22:55:39 INFO]: Smartjer123[/10.14.0.4:45640] logged in with entity id 218 at ([world]-174.0, 142.0, -19.0) 
**How/when does this happen**: 
This happens when a player joins

**Comment by jiangdashao** [comment]
Please delete your old config files
