### ISSUE TITLE
Playermoveevent error on 1.13.2

### ISSUE THREAD

**Issue by OverBrave** [jiangdashao/Matrix-Issues#5]
### Issue description
[13:28:13 ERROR]: Could not pass event PlayerMoveEvent to Matrix v1.0.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-521]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-521]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-521]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1062) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-521]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-521]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-521]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
at me.rerere.matrix.IiIIiIIiIi.iiiiIIIiII(m) ~[?:?]
at me.rerere.matrix.IIIiiIIIIi.iIIiiIIiIi(qb) ~[?:?]
at me.rerere.matrix.IIiiIiiIIi.iIIiiIIiIi(ya) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor304.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-521]
... 15 more

### Core information
** Matrix Version **: Last version
** Server Version **: 1.13.2
** ProtocolLib Version **: Last version

### Other infomation
** ProtocolSupport Version: 
![image](https://user-images.githubusercontent.com/47111280/52533018-b9cdb800-2d3e-11e9-95f2-f61a9fe58b35.png)

**Comment by jiangdashao** [comment]
Please provide server log

**Comment by OverBrave** [comment]
[2019-02-10-13.log](https://github.com/jiangdashao/Matrix-Issues/files/2848799/2019-02-10-13.log)

**Comment by jiangdashao** [comment]
It will be fixed in 1.0.7
