### ISSUE TITLE
errors in the console

### ISSUE THREAD

**Issue by JakubEG0** [jiangdashao/Matrix-Issues#50]
## Console Error

Could not pass event PlayerMoveEvent to Matrix v1.5.4
java.lang.NullPointerException: null
at me.rerere.matrix.IIiIIiIiII.iIIIiiIiii(ib) ~[?:?]
at me.rerere.matrix.iiIIiiIiII.iIIIiiIiii(da) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-566]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-566]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-566]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:437) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.PacketPlayInVehicleMove.a(SourceFile:48) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.PacketPlayInVehicleMove.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-566]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-566]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-566]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

## When the error happens?
Today (I think)

# Server Infomation
**Server Version**: 1.13.2
**Matrix Version**: newest
**ProtocolLib Version**: newest
**Is you config files newest?**: yes

**Comment by jiangdashao** [comment]
When the error happens? = How you trigger the error?

**Comment by JakubEG0** [comment]
I do not know..

**Comment by jiangdashao** [comment]
...

**Comment by jiangdashao** [comment]
It seems caused by Vehicle move, did you sit in any vehicle?
