### ISSUE TITLE
[ERROR] Some Warning in the console

### ISSUE THREAD

**Issue by SamLam140330** [jiangdashao/Matrix-Issues#512]
Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

**Server version**: Spigot-d05d3c1-7ffb2a2 (MC: 1.14.3)
**Error(s) found in console**: 0 Warn: 33
**How/when does this happen**: When Matrix Anti Cheat is updated to 2.0.4 hoxfix
**Other information**: It still work (I think), just have many warning

**Link to checks.yml file**:  https://pastebin.com/s9VJ0Nea
**Link to config.yml file**:  https://pastebin.com/NUjnZUh3
Full Server log:  https://pastebin.com/aehWK9nr

**Comment by SamLam140330** [comment]
Sorry, what does "can't reproduce" means?

**Comment by jiangdashao** [comment]
There isn't any error in my test

**Comment by SamLam140330** [comment]
I have already retest my server and remove all other plugins and use the default setting of matrix but still come with an error.

[21:58:51] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 4, column 10:
        pitch: 12.925314903259277
             ^
[21:58:51] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
[21:58:51] [Server thread/WARN]: 	at me.rerere.matrix.iiiIIIiIIi.IIIIiiiIII(hb)
[21:58:51] [Server thread/WARN]: 	at me.rerere.matrix.Matrix.onEnable(hk)
[21:58:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:58:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[21:58:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[21:58:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[21:58:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[21:58:51] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439)
[21:58:51] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[21:58:51] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764)
[21:58:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:58:51] [Server thread/WARN]: Caused by: mapping values are not allowed here
 in 'string', line 4, column 10:
        pitch: 12.925314903259277
             ^
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[21:58:51] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
[21:58:51] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
[21:58:51] [Server thread/WARN]: 	... 11 more
