### ISSUE TITLE
[ERROR]  Cannot translate null text at org.apache.commons.lang.Validate.notNull

### ISSUE THREAD

**Issue by unclemusclez** [jiangdashao/Matrix-Issues#554]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: ```git-Spigot-9de398a-8b09d98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)```
**Error(s) found in console**: ```[16:18:28] [Server thread/ERROR]: Error occurred while enabling Matrix v2.0.6 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot translate null text
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at me.rerere.matrix.IiiIIIiIiI.a(bg) ~[?:?]
        at me.rerere.matrix.IiiIIIiIiI.IiiIiIiIIi(bg) ~[?:?]
        at me.rerere.matrix.IiIiIiIIIi.IiiIiIiIIi(ph) ~[?:?]
        at me.rerere.matrix.Matrix.onEnable(tl) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```
**How/when does this happen**: On Startup
**Other information**: Discord Chats suggests I switch to v1.8 to fix issue.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by ZakShearman** [comment]
Can you try to reset your configuration files and see if that changes anything?

**Comment by unclemusclez** [comment]
> Can you try to reset your configuration files and see if that changes anything?

they are the default ones that are generated on a new install. i backed up and removed the original Matrix folder

**Comment by unclemusclez** [comment]
upgrade 2.0.7 solved error
