### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by Pas02** [jiangdashao/Matrix-Issues#583]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
Spigot 1.8.8 R3
**Error(s) found in console**: 
[05:05:52] [Server thread/ERROR]: Error occurred while enabling Matrix v2.0.7 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at me.rerere.matrix.iIiiiIIiIi.a(le) ~[?:?]
	at me.rerere.matrix.iIiiiIIiIi.iIiiiiIIII(le) ~[?:?]
	at me.rerere.matrix.iiIiiIIiII.iIiiiiIIII(ef) ~[?:?]
	at me.rerere.matrix.Matrix.onEnable(vi) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
**How/when does this happen**: 
Startup of Server -> when the Plugin loads
**Other information**: 
-
## Configuration Files
**Link to checks.yml file**: 
https://pastebin.com/4E5kLEZs
**Link to config.yml file**:
https://pastebin.com/QH7mQsyR

**Comment by jiangdashao** [comment]
delete your old config files, include config.yml & checks.yml & language.yml

**Comment by Pas02** [comment]
it worked, thanks :)
