### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by B4TT3RY** [jiangdashao/Matrix-Issues#689]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-175 (MC 1.14.4)
**Error(s) found in console**: 
```
[00:04:19 ERROR]: Could not pass event BlockPlaceEvent to Matrix v2.2.4
java.lang.NullPointerException: null
at me.rerere.matrix.IIiiIIIIiI.IiiIIIIiii(vf) ~[?:?]
at me.rerere.matrix.iIiiiiIIiI.IiiIIIIiii(ne) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor211.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-175]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:324) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:231) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:500) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-175]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-175]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
**How/when does this happen**: Maybe Block Place?
**Other information**: -

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Please delete your old config files

**Comment by B4TT3RY** [comment]
> Please delete your old config files

It was immediately after installing the plugin on the main server.

**Comment by jiangdashao** [comment]
try next version

**Comment by B4TT3RY** [comment]
> try next version

But 2.2.4 is latest version.
Do you have a different version?

**Comment by jiangdashao** [comment]
I will release 2.2.5 soon
