### ISSUE TITLE
Error occurred while enabling Matrix v2.2.8

### ISSUE THREAD

**Issue by SPYmeYT** [jiangdashao/Matrix-Issues#710]
[22:01:49] [Server thread/ERROR]: Error occurred while enabling Matrix v2.2.8 (Is it up to date?)
java.lang.NullPointerException: null
	at me.rerere.matrix.IiIiiiiiIi.iiiIiiiIii(bd) ~[?:?]
	at me.rerere.matrix.iIIiiiiiII.iiiIiiiIii(re) ~[?:?]
	at me.rerere.matrix.Matrix.onEnable(tl) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[core.jar:git-Paper-1568]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[core.jar:git-Paper-1568]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[core.jar:git-Paper-1568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[core.jar:git-Paper-1568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[core.jar:git-Paper-1568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[core.jar:git-Paper-1568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[core.jar:git-Paper-1568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[core.jar:git-Paper-1568]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[core.jar:git-Paper-1568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[core.jar:git-Paper-1568]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by NgLoader** [comment]
More details?

Server verison: ?
ProtocolLib version: ?

**Comment by JaroSound** [comment]
Same on spigot 1.14.4

**Comment by True-cc** [comment]
You did reset your config file (checks.yml config.yml etc) because you know that it can't autoupdate, right?

**Comment by SPYmeYT** [comment]
Yes, broken config, problem solved by deleting it.
