### ISSUE TITLE
Task #822 error

### ISSUE THREAD

**Issue by senseirabbin** [jiangdashao/Matrix-Issues#78]
## Console Error

[WARNING] [Matrix] Task #822 for Matrix v1.7.4 generated an exception

java.lang.NoClassDefFoundError: com.comphenix.protocol.injector.PacketConstructor (initialization failure)

at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96) ~[?:1.8.0_192]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]

at me.rerere.matrix.IiIiiiIIIi.IIIIIiiIIi(db) ~[?:?]

at me.rerere.matrix.iiiiiiiIIi.run(ie) ~[?:?]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

Caused by: java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError

at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:531) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:129) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

... 4 more

Caused by: java.lang.ExceptionInInitializerError

at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146) ~[?:1.8.0_192]

at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843) ~[?:1.8.0_192]

at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:531) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:129) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

... 4 more

Caused by: java.lang.IllegalArgumentException: Unable to find findStatistic in net.minecraft.server.v1_13_R2.StatisticList

at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280) ~[?:?]

at com.comphenix.protocol.wrappers.WrappedStatistic.<clinit>(WrappedStatistic.java:22) ~[?:?]

at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843) ~[?:1.8.0_192]

at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:531) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:129) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]

... 4 more
**Also the Protocolib gives this error**

https://pastebin.com/Te9pkDLq

## When the error happens?

Whenever I start the server with Martrix on this happens. When i put Martrix and protocolib off and reload the server runs fine. This message is spammed infite times.

# Server Infomation
**Server Version**: Version 1.13.2
**Matrix Version**: 1.7.4
**ProtocolLib Version**: ProtocolLib 4.4.0
**Is you config files newest?**: (**yes**/no)

**Comment by jiangdashao** [comment]
Please re-download the ProtocolLib, I think it's not Matrix's bug
