### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by InfinityMage** [jiangdashao/Matrix-Issues#787]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 (Paper-187)
**Error(s) found in console**: 
`>.... [07:15:00 WARN]: [Matrix] Task #52 for Matrix v2.3.8 generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
at me.rerere.matrix.iIIIiiiIii.iiIIiiIIII(ak) ~[?:?]
at me.rerere.matrix.iiiiIIIiiI.run(lo) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-187]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**How/when does this happen**: As soon as a player joins the server, the console immediately fills up with this error and doesn't stop.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default file
**Link to config.yml file**: default file

**Comment by jiangdashao** [comment]
Update ProtocolLib to 4.5.0
