### ISSUE TITLE
[ERROR Cannot Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by cakebomb999** [jiangdashao/Matrix-Issues#79]
## Console Error
[14:02:31 ERROR]: Could not pass event PlayerJoinEvent to Matrix v1.7.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:162) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:149) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at me.rerere.matrix.IiiiiIiiii.<init>(eo) ~[?:?]
        at me.rerere.matrix.IIiiIIiIII.<init>(xm) ~[?:?]
        at me.rerere.matrix.IiIIIiiiii.<init>(v) ~[?:?]
        at me.rerere.matrix.IIiiiIiiiI.IIIIIiiIIi(q) ~[?:?]
        at me.rerere.matrix.IIiiiIiiiI.IIIIIiiIIi(q) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot.jar:git-Spigot-e6eb36f-51100db]
        ... 14 more
[14:02:31 INFO]: _chris2003[/91.211.11.219:51475] logged in with entity id 5112 at ([world]-194.0, 89.0, -110.0)
[14:02:31 WARN]: [PlayTime] Plugin PlayTime v1.1 generated an exception while executing task 17254
java.lang.NoSuchFieldError: PLAY_ONE_TICK
        at me.MiniDigger.OnlineTime.OnlineTime.OnlineTime.checkForReward(OnlineTime.java:218) ~[?:?]
        at me.MiniDigger.OnlineTime.OnlineTime.OnlineTime.lambda$onJoin$3(OnlineTime.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-e6eb36f-51100db]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-e6eb36f-51100db]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

## When the error happens?
Everytime a player joins

# Server Infomation
**Server Version**: 1.13.2
**Matrix Version**: 1.7.4
**ProtocolLib Version**: 4.4.0
**Is you config files newest?**: (yes)

**Comment by jiangdashao** [comment]
Please delete your checks.yml, and try again
