### ISSUE TITLE
[ERROR] - Not sure 

### ISSUE THREAD

**Issue by polo002** [jiangdashao/Matrix-Issues#947]
14:09:54 INFO]: [Matrix] Enabling Matrix v2.6.7
[14:09:54 INFO]: _____
[14:09:54 INFO]: | | | Matrix AntiCheat v2.6.7
[14:09:54 INFO]: | | | Environment: git-Paper-223 (MC: 1.14.4)
[14:09:54 INFO]:
[14:09:54 INFO]: [Matrix] Enabled 15 checks, Disabled 0 checks
[14:09:54 ERROR]: Error occurred while enabling Matrix v2.6.7 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot translate null text
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.4.jar:git-Paper-223]
at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.14.4.jar:git-Paper-223]
at me.rerere.matrix.iiiIIiIiIi.a(lg) ~[?:?]
at me.rerere.matrix.iiiIIiIiIi.iIIiiIiIii(lg) ~[?:?]
at me.rerere.matrix.iIiiiiIIIi.iIIiiIiIii(en) ~[?:?]
at me.rerere.matrix.Matrix.onEnable(ch) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-223]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-223]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-223]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-223]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-223]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-223]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-223]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-223]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[14:09:54 INFO]: [Matrix] Disabling Matrix v2.6.7
[14:09:54 INFO]: [Matrix] Error when disabling Matrix: java.lang.NullPointerException
[14:09:54 INFO]: [Matrix] Disabled Matrix AntiCheat.

**Comment by ZakShearman** [comment]
Did you update from a previous Matrix version?

**Comment by jiangdashao** [comment]
delete your config files
