### ISSUE TITLE
[ERROR] NPE

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#955]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
this did not occur on startup, just randomly
*>.... [20:45:52 ERROR]: Could not pass event BlockBreakEvent to Matrix v2.6.8
java.lang.IllegalStateException: Start block missed in BlockIterator
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:171) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:236) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:277) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:172) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:189) ~[patched_1.14.4.jar:git-Paper-221]
at me.rerere.matrix.iiIIIiiiII.IIiIiIiIii(dh) ~[?:?]
at me.rerere.matrix.iiiiiiIIiI.IIiIiIiIii(kk) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor292.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-221]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-221]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:303) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:262) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:236) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-221]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-221]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]*

**Comment by ZakShearman** [comment]
Did you reset your config.yml if you updated from a prior version, and if necessary, checks.yml?

**Comment by Olly32** [comment]
yes, I have been updating my checks and config correctly every update.

**Comment by jiangdashao** [comment]
Ignore it, it's not important, and it won't influence Matrix working.
