### ISSUE TITLE
[ERROR] Plugin not loading ?

### ISSUE THREAD

**Issue by At0micA55** [jiangdashao/Matrix-Issues#979]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Error(s) found in console**:
``` 
18.11 13:42:22 [Server] Server thread/INFO _____
18.11 13:42:22 [Server] Server thread/INFO |  |  |   Matrix AntiCheat v2.7.0
18.11 13:42:22 [Server] Server thread/INFO |  |  |   Environment: git-Spigot-56f8471-56118c6 (MC: 1.14.4)
18.11 13:42:22 [Server] Server thread/INFO [Matrix] Enabled 16 checks, Disabled 0 checks
18.11 13:42:22 [Server] Server thread/ERROR Error occurred while enabling Matrix v2.7.0 (Is it up to date?)
18.11 13:42:22 [Server] INFO java.lang.IllegalArgumentException: Cannot translate null text
18.11 13:42:22 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at me.rerere.matrix.IIiIiiIiii.a(Unknown Source) ~[?:?]
18.11 13:42:22 [Server] INFO at me.rerere.matrix.IIiIiiIiii.IIiiiIIIii(Unknown Source) ~[?:?]
18.11 13:42:22 [Server] INFO at me.rerere.matrix.IiIiIiiiII.IIiiiIIIii(Unknown Source) ~[?:?]
18.11 13:42:22 [Server] INFO at me.rerere.matrix.Matrix.onEnable(Unknown Source) ~[?:?]
18.11 13:42:22 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot.jar:git-Spigot-56f8471-56118c6]
18.11 13:42:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot.jar:git-Spigot-56f8471-56118c6]
```

**How/when does this happen**: Every startup of the server ! (NOT reload... Full stop and start)
**Other information**: none ?

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/Uu3GVDri
**Link to config.yml file**: https://pastebin.com/WpqLzE9F

**Comment by At0micA55** [comment]
when i do /matrix the result is only

/matrix <params> 

If i do /matrix gui or GUI i still get the /matrix <params> text

**Comment by ZakShearman** [comment]
If you updated from a previous version, you most likely did not follow the necessary update instructions.  Please delete your checks.yml and config.yml.

**Comment by At0micA55** [comment]
Will try to delete the config too but the checks i already deleted it and it didn't change the loading problem

**Comment by jiangdashao** [comment]
delete language.yml

**Comment by At0micA55** [comment]
Will close this issue now cause getting rid both of the Checks.yml and Config.yml solved the problems ! Thank you @ZakShearman
